### ISSUE TITLE
Project maintainable?

### ISSUE THREAD

**Issue by Madi-S** [SinoLewis/finance-analyst#1]
Hey,

Great project. Just wanted to inquire if this project is still being maintained? Or what kind of maintation does it require.
I am open to collaboration or contribution, just let me know, what needs to be done to maintain the project as an open source program.

Moreover, are there any existing flaws or features yet to be implemented for this project?

**Comment by SinoLewis** [comment]
Hey Madi, Firstly i thank you for your interest in the project. I partially
maintain the project from time to time and lately I have aimed to provide
its starter code  so that it may be open for community contributions. I
didn't respond to the github issue as i was not aware. So if you are
interested, we can keep in touch via github or email.
